c=(56,658,65,68)
a=(56,95,56,"hello")
b=(56,95,96,"hjf","world")
print(a+b)
#print(a-b) not working
print((a+b).__len__())
print(max(c))
print(min(c))
st=("manpreet","singh","chahal")
print(st)
print(st.__sizeof__())
print(b.__sizeof__())